name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: |
          curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
          export PATH="$HOME/.pnpm-global/bin:$PATH"
          echo "::add-path::$HOME/.pnpm-global/bin"
          pnpm --version

      - name: Install dependencies
        run: |
          pnpm install
          # Install any additional dependencies needed for your project

      - name: Build
        run: pnpm run build
        # Modify the build command as needed for your SvelteKit project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
